### ISSUE TITLE
Localized contents in /insightsbeta and /insights are not shown

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-frontend#482] opened 2018-06-05 03:19 UTC
Though I choose Japanese as the default language of Customer Portal, /insightsbeta and /insights still show English contents.

https://access.redhat.com/insightsbeta/overview/

**Comment by jharting** [comment] 2018-06-05 15:40
@koalakangaroo Seems to work if I set a cookie `rh_locale: ja_JP`. What cookie does CP give you?

**Comment by koalakangaroo** [comment] 2018-06-05 23:10
@jharting - Here is my test: 

1. I access https://access.redhat.com.
2. I changed the language to Japanese and all contents are displayed in Japanese.
3. I check the cookie and it shows "rh_locale: ja".
4. I access https://access.redhat.com/insights/overview by clicking Tools->Red Hat Insights Learn More (on the right side).
5. All contents are displayed in English.
6. I check the cookie and it shows "rh_locale: en_US".
7. I manually change the rh_locale in the cookie to ja and it shows Japanese contents.

It seems that the rh_locale is not consistent at least in my browser.

**Comment by koalakangaroo** [comment] 2018-06-19 01:37
@jharting - After you merged https://github.com/RedHatInsights/insights-frontend/pull/484, the latest Japanese content can not be shown as expected. The reproduce steps above make this issue every time.

**Comment by koalakangaroo** [comment] 2018-06-21 00:15
@jharting - #484 just added the new Japanese translation po file. This issue was opened for the problem that Japanese is not displayed in Insights web ui. 

No matter which browser I am using (Firefox and Safari), Japanese contents are not displayed in Insights web ui though I chose Japanese as the language in Customer Portal. I can see Japanese contents in Customer Portal except Insights pages.

**Comment by koalakangaroo** [comment] 2018-08-13 23:27
@jharting - Any update on this issue? To make this issue easier to understand, I recorded a small video (mp4) for your reference. (Please rename the suffix from gif to mp4 after you download it)

![localization_failure](https://user-images.githubusercontent.com/15642756/44063470-f11b7b9a-9fa3-11e8-9471-d8b93dfc2256.gif)

The brief reproduce steps:
1. Set default language as Japanese on Customer Portal and everything in the Portal is displayed in Japanese
2. Enter Insights UI
3. Insights UI displays English version

3. The

**Comment by jharting** [comment] 2018-08-14 13:10
@koalakangaroo apologies for the delay. I lost track of this. Looks like the rh_locale is overwritten to "en_US" by SSO. More specifically the response from https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/auth?client_id=... contains `Set-Cookie: rh_locale=en_US; Domain=.redhat.com;...`

**Comment by iphands** [comment] 2018-08-14 13:40
@jharting @koalakangaroo hrrmmm

So when you are using SSO, however weird it might be, the contract that exists is that the SSO app will set-cookie to whatever your Users preferred language is in the SSO data base (as far as I know).

Can you verify when reproducing this that your Users language preference is correct in SSO?

**Comment by jharting** [comment] 2018-08-14 13:44
@iphands is "SSO data base" the same thing as https://www.redhat.com/wapps/ugc/protected/locale.html ?

I can verify that after submitting the form at https://www.redhat.com/wapps/ugc/protected/locale.html I get `ja` cookie but then afterwards I get `en_US` if I querry sso.redhat.com

**Comment by iphands** [comment] 2018-08-14 13:49
Yeah SSO should honor the setting at https://www.redhat.com/wapps/ugc/protected/locale.html as far as I know.

**Comment by jharting** [comment] 2018-08-14 13:57
@iphands ok, looks like that things is broken then

**Comment by iphands** [comment] 2018-08-14 14:19
@jharting hrrrmmmm so I noticed the same thing you did. BUT, the UGC app says something about "must log out" before changes are effective.

If I set my locale to Japanese in UGC, then open a fresh browser session, then follow Jaylins repro steps I end up on a JA Insights.

**Comment by koalakangaroo** [comment] 2018-08-14 22:45
@iphands  @jharting - thanks for your confirmation. I reviewed your discussion in emails.

**Comment by koalakangaroo** [comment] 2019-04-09 04:14
@iphands @jharting - a QE from i18n team faced the same problem - JA Locale is leaping to English when accessing Insights Classic. Do we have any update about this issue?
![image](https://user-images.githubusercontent.com/15642756/55772902-aa19e800-5ad1-11e9-91c5-0d087ae24546.png)

**Comment by iphands** [comment] 2019-04-13 01:42
@koalakangaroo Jozef and I no longer write or maintain Insights Classic.
I think @kensible can help

**Comment by kensible** [comment] 2019-04-15 12:54
I'm going to discuss this bug with Rob Williams and we'll figure out where it falls in the backlog with the Summit deliverables coming up and the Insights Classic UI being removed with the launch of the new Cloud Management offerings.

**Comment by kensible** [comment] 2019-04-15 13:14
@koalakangaroo @iphands After discussing with Rob this will not be fixed as the Classic UI is going away in 22 days. Currently, the new Insights only supports English but we'll address this regression post-Summit after the UI stabilizes. Closing the bug and opening a Jira for the work after Summit: https://projects.engineering.redhat.com/browse/RHCLOUD-744

**Closed by kensible** 2019-04-15 13:14 UTC
